schemaVersion = "2.0"
id = "lcod://tooling/json/read_file@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Read and parse a JSON file from disk."

[palette]
category = "JSON"
icon = "mdi:file-json"
tags = [ "json", "io" ]

[deps]
requires = [
  "lcod://impl/set@1",
  "lcod://flow/if@1",
  "lcod://axiom/path/join@1",
  "lcod://axiom/fs/read-file@1",
  "lcod://core/json/decode@0.1.0"
]

[inputs.basePath]
summary = "Base directory joined with the JSON path."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.path]
summary = "Path to the JSON file."
required = true
schema = """
{
  "type": "string"
}"""

[inputs.encoding]
summary = "File encoding (defaults to utf-8)."
required = false
schema = """
{
  "type": "string"
}"""

[outputs.path]
summary = "Resolved absolute path."
schema = """
{
  "type": "string"
}"""

[outputs.value]
summary = "Parsed JSON value."
schema = "{}"

[documentation]
body = "Read and parse a JSON file from disk."

[docs]
readme = "README.md"
