
schemaVersion = "1.0"
id = "lcod://tooling/array/length@0.1.0"
name = "length"
namespace = "tooling/array"
version = "0.1.0"
kind = "component"
summary = "Return the length of an array (0 if not an array)."

[deps]
requires = [
  "lcod://tooling/script@1"
]
