schemaVersion = "2.0"
id = "lcod://tooling/mcp/session/open@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Create or reuse a workspace folder for MCP authoring sessions."

[palette]
category = "Authoring"
icon = "mdi:folder-open"
tags = [ "mcp", "workspace", "authoring" ]

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://axiom/path/join@1",
  "lcod://axiom/fs/write-file@1"
]

[inputs.workspaceRoot]
summary = "Absolute or relative path where session workspaces should be created."
required = true
schema = """
{
  "type": "string"
}"""

[inputs.sessionId]
summary = "Optional session identifier; when omitted a new identifier is generated."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.componentId]
summary = "Optional component ID linked to the session (stored in provenance metadata)."
required = false
schema = """
{
  "type": "string"
}"""

[outputs.sessionId]
summary = "Identifier assigned to the session workspace."
schema = """
{
  "type": "string"
}"""

[outputs.workspaceRoot]
summary = "Base directory that contains the session workspaces."
schema = """
{
  "type": "string"
}"""

[outputs.workspacePath]
summary = "Absolute path to the session workspace."
schema = """
{
  "type": "string"
}"""

[outputs.provenancePath]
summary = "Path to the generated provenance file for this session."
schema = """
{
  "type": "string"
}"""
