schemaVersion = "1.0"
id = "lcod://tooling/mcp/session/open@0.1.0"
name = "open"
namespace = "tooling/mcp/session"
version = "0.1.0"
kind = "component"

summary = "Create or reuse a workspace folder for MCP authoring sessions."

[palette]
category = "Authoring"
icon = "mdi:folder-open"
tags = ["mcp", "workspace", "authoring"]

[docs]
readme = "docs/README.md"

[[io.input]]
name = "workspaceRoot"
type = "string"
required = true
description = "Absolute or relative path where session workspaces should be created."

[[io.input]]
name = "sessionId"
type = "string"
required = false
description = "Optional session identifier; when omitted a new identifier is generated."

[[io.input]]
name = "componentId"
type = "string"
required = false
description = "Optional component ID linked to the session (stored in provenance metadata)."

[[io.output]]
name = "sessionId"
type = "string"
description = "Identifier assigned to the session workspace."

[[io.output]]
name = "workspaceRoot"
type = "string"
description = "Base directory that contains the session workspaces."

[[io.output]]
name = "workspacePath"
type = "string"
description = "Absolute path to the session workspace."

[[io.output]]
name = "provenancePath"
type = "string"
description = "Path to the generated provenance file for this session."

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://axiom/path/join@1",
  "lcod://axiom/fs/write-file@1"
]
