schemaVersion = "1.0"
id = "lcod://pkg/std@0.1.0"
name = "std"
namespace = "pkg"
version = "0.1.0"
kind = "workspace-package"

[workspace]
components = [
  "lcod://tooling/array/append@0.1.0",
  "lcod://tooling/array/compact@0.1.0",
  "lcod://tooling/array/find_duplicates@0.1.0",
  "lcod://tooling/array/flatten@0.1.0",
  "lcod://tooling/array/length@0.1.0",
  "lcod://tooling/array/pluck@0.1.0",
  "lcod://tooling/fs/write_if_changed@0.1.0",
  "lcod://tooling/json/read_file@0.1.0",
  "lcod://tooling/json/stringify@0.1.0",
  "lcod://tooling/jsonl/from_objects@0.1.0",
  "lcod://tooling/registry_catalog/collect@0.1.0",
  "lcod://tooling/registry_catalog/duplicate_package_errors@0.1.0",
  "lcod://tooling/registry_catalog/normalize_catalog@0.1.0",
  "lcod://tooling/registry_catalog/normalize_package@0.1.0",
  "lcod://tooling/registry_catalog/normalize_registry@0.1.0",
  "lcod://tooling/registry_catalog/normalize_version@0.1.0",
  "lcod://tooling/registry_catalog/normalize_versions_doc@0.1.0",
  "lcod://tooling/registry_catalog/packages_map@0.1.0",
  "lcod://tooling/registry_catalog/refresh@0.1.0",
  "lcod://tooling/registry_catalog/validate@0.1.0",
  "lcod://tooling/registry_catalog/validate_package@0.1.0",
  "lcod://tooling/registry_catalog/write_outputs@0.1.0",
  "lcod://tooling/string/ensure_trailing_newline@0.1.0",
  "lcod://tooling/value/is_array@0.1.0",
  "lcod://tooling/value/is_object@0.1.0",
  "lcod://tooling/value/is_string_nonempty@0.1.0"
]
