schemaVersion = "1.0"
id = "lcod://tooling/fs/write_if_changed@0.1.0"
name = "write_if_changed"
namespace = "tooling/fs"
version = "0.1.0"
kind = "component"

summary = "Write a file only when the content differs."

[palette]
category = "Filesystem"
icon = "mdi:file-replace"
tags = ["fs", "io"]

[docs]
readme = "README.md"

[[io.input]]
name = "path"
type = "string"
required = true
description = "Destination file path."

[[io.input]]
name = "content"
type = "string"
required = false
description = "Content written to the file (coerced to string)."

[[io.input]]
name = "encoding"
type = "string"
required = false
description = "Encoding used when reading existing content (defaults to utf-8)."

[[io.output]]
name = "changed"
type = "boolean"
description = "True when the file was rewritten."

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://axiom/fs/read-file@1",
  "lcod://axiom/fs/write-file@1"
]
