schemaVersion = "2.0"
id = "lcod://tooling/fs/write_if_changed@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Write a file only when the content differs."

[palette]
category = "Filesystem"
icon = "mdi:file-replace"
tags = [ "fs", "io" ]

[deps]
requires = [ "lcod://contract/tooling/fs/write_if_changed@1" ]

[inputs.path]
summary = "Destination file path."
required = true
schema = """
{
  "type": "string"
}"""

[inputs.content]
summary = "Content written to the file (coerced to string)."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.encoding]
summary = "Encoding used when reading existing content (defaults to utf-8)."
required = false
schema = """
{
  "type": "string"
}"""

[outputs.changed]
summary = "True when the file was rewritten."
schema = """
{
  "type": "boolean"
}"""

[documentation]
body = "Write a file only when the content differs."
