
schemaVersion = "1.0"
id = "lcod://tooling/fs/write_if_changed@0.1.0"
name = "write_if_changed"
namespace = "tooling/fs"
version = "0.1.0"
kind = "component"
summary = "Write a file only if the content differs from the current value."

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://axiom/fs/read-file@1",
  "lcod://axiom/fs/write-file@1"
]
