
schemaVersion = "1.0"
id = "lcod://tooling/value/is_array@0.1.0"
name = "is_array"
namespace = "tooling/value"
version = "0.1.0"
kind = "component"
summary = "Check whether a value is an array."

[deps]
requires = [
  "lcod://tooling/script@1"
]
