schemaVersion = "1.0"
id = "lcod://tooling/array/flatten@0.1.0"
name = "flatten"
namespace = "tooling/array"
version = "0.1.0"
kind = "component"
summary = "Flatten a list of arrays into a single array (one level deep)."

[deps]
requires = [
  "lcod://tooling/script@1"
]
