schemaVersion = "2.0"
id = "lcod://tooling/array/flatten@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Flatten an array one level deep."

[palette]
category = "Array"
icon = "mdi:arrange-bring-forward"
tags = [ "array", "transform" ]

[deps]
requires = [ "lcod://contract/tooling/array/flatten@1" ]

[inputs.items]
summary = "Nested array or scalar values to flatten."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.values]
summary = "Flattened sequence preserving order."
schema = """
{
  "type": "array"
}"""

[documentation]
body = "Flatten an array one level deep."
