schemaVersion = "1.0"
id = "lcod://tooling/registry_sources/collect_entries@0.1.0"
name = "collect_entries"
namespace = "tooling/registry_sources"
version = "0.1.0"
kind = "component"

summary = "Fetch registry catalogues from the sources configuration and emit inline registry source entries."

[palette]
category = "Registry"
icon = "mdi:cloud-download"
tags = ["registry", "catalogue", "sources"]

[docs]
readme = "README.md"

[[io.input]]
name = "sourcesConfig"
type = "object"
required = true
description = "Parsed sources specification."

[[io.input]]
name = "sourcesBaseDir"
type = "string"
required = true
description = "Base directory used to resolve relative catalogue paths."

[[io.input]]
name = "downloadsRoot"
type = "string"
required = true
description = "Directory dedicated to downloaded catalogues."

[[io.output]]
name = "registrySources"
type = "array"
description = "Inline registry source entries derived from the catalogues."

[[io.output]]
name = "warnings"
type = "array"
description = "Warnings emitted while fetching and parsing catalogues."

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://contract/core/fs/read-file@1",
  "lcod://contract/core/git/clone@1",
  "lcod://axiom/http/download@1",
  "lcod://tooling/path/join_chain@0.1.0",
  "lcod://tooling/path/dirname@0.1.0",
  "lcod://tooling/path/is_absolute@0.1.0",
  "lcod://tooling/path/to_file_url@0.1.0",
  "lcod://tooling/hash/sha256_base64@0.1.0"
]
