schemaVersion = "1.0"
id = "lcod://tooling/registry_catalog/packages_map@0.1.0"
name = "packages_map"
namespace = "tooling/registry_catalog"
version = "0.1.0"
kind = "component"

summary = "Build the registry packages map from package metadata."

[palette]
category = "Registry/Internal"
icon = "mdi:map-legend"
tags = ["catalog", "mapping"]

[docs]
readme = "README.md"

[[io.input]]
name = "entries"
type = "array"
required = false
description = "Package registry references."

[[io.output]]
name = "map"
type = "object"
description = "Mapping suitable for registry.json."

[deps]
requires = [
  "lcod://tooling/script@1"
]
