schemaVersion = "2.0"
id = "lcod://tooling/registry_catalog/packages_map@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Build the registry packages map from package metadata."

[palette]
category = "Registry/Internal"
icon = "mdi:map-legend"
tags = [ "catalog", "mapping" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.entries]
summary = "Package registry references."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.map]
summary = "Mapping suitable for registry.json."
schema = """
{
  "type": "object"
}"""

[documentation]
body = "Build the registry packages map from package metadata."
