schemaVersion = "1.0"
id = "lcod://tooling/registry_catalog/packages_map@0.1.0"
name = "packages_map"
namespace = "tooling/registry_catalog"
version = "0.1.0"
kind = "component"
summary = "Convert package registry references into the registry.json packages map."

[deps]
requires = [
  "lcod://tooling/script@1"
]
