
schemaVersion = "1.0"
id = "lcod://tooling/registry_catalog/duplicate_package_errors@0.1.0"
name = "duplicate_package_errors"
namespace = "tooling/registry_catalog"
version = "0.1.0"
kind = "component"
summary = "Produce error messages for duplicate package ids in the catalog."

[deps]
requires = [
  "lcod://tooling/script@1"
]
