schemaVersion = "1.0"
id = "lcod://tooling/registry_catalog/duplicate_package_errors@0.1.0"
name = "duplicate_package_errors"
namespace = "tooling/registry_catalog"
version = "0.1.0"
kind = "component"

summary = "Produce error messages for duplicate package identifiers."

[palette]
category = "Registry/Internal"
icon = "mdi:alert-circle-outline"
tags = ["catalog", "validation"]

[docs]
readme = "README.md"

[[io.input]]
name = "duplicates"
type = "array"
required = false
description = "Duplicate package identifiers."

[[io.output]]
name = "errors"
type = "array"
description = "Error messages for each duplicate package id."

[deps]
requires = [
  "lcod://tooling/script@1"
]
