schemaVersion = "2.0"
id = "lcod://tooling/registry_catalog/duplicate_package_errors@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Produce error messages for duplicate package identifiers."

[palette]
category = "Registry/Internal"
icon = "mdi:alert-circle-outline"
tags = [ "catalog", "validation" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.duplicates]
summary = "Duplicate package identifiers."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.errors]
summary = "Error messages for each duplicate package id."
schema = """
{
  "type": "array"
}"""

[documentation]
body = "Produce error messages for duplicate package identifiers."

[docs]
readme = "README.md"
