
schemaVersion = "1.0"
id = "lcod://tooling/array/find_duplicates@0.1.0"
name = "find_duplicates"
namespace = "tooling/array"
version = "0.1.0"
kind = "component"
summary = "Find duplicate string values in an array (case-sensitive)."

[deps]
requires = [
  "lcod://tooling/script@1"
]
