schemaVersion = "2.0"
id = "lcod://tooling/array/find_duplicates@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Return duplicated string values present in an array."

[palette]
category = "Array"
icon = "mdi:alert-octagon-outline"
tags = [ "array", "dedupe" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.items]
summary = "Array inspected for duplicate string values."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.duplicates]
summary = "Unique list of duplicated strings."
schema = """
{
  "type": "array"
}"""

[documentation]
body = "Return duplicated string values present in an array."
