schemaVersion = "2.0"
id = "lcod://tooling/registry_catalog/normalize_version@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Normalise a single package version entry."

[palette]
category = "Registry/Internal"
icon = "mdi:tag-outline"
tags = [ "catalog", "normalize" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.packageId]
summary = "Parent package identifier."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.registryId]
summary = "Registry identifier applied to the version."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.packagePriority]
summary = "Default priority declared at package level."
required = false
schema = """
{
  "type": "number"
}"""

[inputs.entry]
summary = "Version entry to normalise."
required = true
schema = """
{
  "type": "object"
}"""

[outputs.ok]
summary = "True when the version entry is valid."
schema = """
{
  "type": "boolean"
}"""

[outputs.line]
summary = "Component line for the JSONL output."
schema = """
{
  "type": "object"
}"""

[outputs.detail]
summary = "Simplified version details used by diagnostics."
schema = """
{
  "type": "object"
}"""

[outputs.warnings]
summary = "Issues detected for the version entry."
schema = """
{
  "type": "array"
}"""

[documentation]
body = "Normalise a single package version entry."
