schemaVersion = "1.0"
id = "lcod://tooling/registry_catalog/normalize_version@0.1.0"
name = "normalize_version"
namespace = "tooling/registry_catalog"
version = "0.1.0"
kind = "component"
summary = "Validate and normalize a package version entry."

[deps]
requires = [
  "lcod://tooling/script@1"
]
