schemaVersion = "2.0"
id = "lcod://tooling/registry_catalog/normalize_catalog@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Normalise the top-level catalog document."

[palette]
category = "Registry/Internal"
icon = "mdi:notebook-check-outline"
tags = [ "catalog", "normalize" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.catalog]
summary = "Catalog document to normalise."
required = false
schema = """
{
  "type": "object"
}"""

[outputs.registries]
summary = "Filtered registry entries."
schema = """
{
  "type": "array"
}"""

[outputs.packages]
summary = "Filtered package entries."
schema = """
{
  "type": "array"
}"""

[outputs.namespaces]
summary = "Namespace configuration."
schema = """
{
  "type": "object"
}"""

[outputs.schema]
summary = "Catalog schema identifier."
schema = """
{
  "type": "string"
}"""

[outputs.warnings]
summary = "Issues detected during normalisation."
schema = """
{
  "type": "array"
}"""

[documentation]
body = "Normalise the top-level catalog document."

[docs]
readme = "README.md"
