schemaVersion = "2.0"
id = "lcod://tooling/array/pluck@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Extract a property from each object in an array."

[palette]
category = "Array"
icon = "mdi:format-list-text"
tags = [ "array", "mapping" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.items]
summary = "Array containing objects."
required = false
schema = """
{
  "type": "array"
}"""

[inputs.field]
summary = "Property name to extract."
required = true
schema = """
{
  "type": "string"
}"""

[outputs.values]
summary = "Extracted property values (undefined when missing)."
schema = """
{
  "type": "array"
}"""

[documentation]
body = "Extract a property from each object in an array."

[docs]
readme = "README.md"
