schemaVersion = "1.0"
id = "lcod://tooling/array/pluck@0.1.0"
name = "pluck"
namespace = "tooling/array"
version = "0.1.0"
kind = "component"
summary = "Extract a property from each object in an array."

[deps]
requires = [
  "lcod://tooling/script@1"
]
