schemaVersion = "1.0"
id = "lcod://tooling/registry_catalog/normalize_registry@0.1.0"
name = "normalize_registry"
namespace = "tooling/registry_catalog"
version = "0.1.0"
kind = "component"
summary = "Validate and normalize a registry entry from the catalog."

[deps]
requires = [
  "lcod://tooling/script@1"
]
