schemaVersion = "2.0"
id = "lcod://tooling/registry_catalog/normalize_registry@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Normalise a registry entry declared in catalog.json."

[palette]
category = "Registry/Internal"
icon = "mdi:server"
tags = [ "catalog", "normalize" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.entry]
summary = "Registry entry to validate."
required = true
schema = """
{
  "type": "object"
}"""

[outputs.ok]
summary = "True when the registry entry is valid."
schema = """
{
  "type": "boolean"
}"""

[outputs.line]
summary = "Registry line inserted into the JSONL output."
schema = """
{
  "type": "object"
}"""

[outputs.warnings]
summary = "Issues detected for the registry entry."
schema = """
{
  "type": "array"
}"""

[documentation]
body = "Normalise a registry entry declared in catalog.json."

[docs]
readme = "README.md"
