schemaVersion = "1.0"
id = "lcod://tooling/jsonl/from_objects@0.1.0"
name = "from_objects"
namespace = "tooling/jsonl"
version = "0.1.0"
kind = "component"

summary = "Convert an array of objects into JSON Lines text."

[palette]
category = "JSON"
icon = "mdi:format-list-bulleted"
tags = ["jsonl", "serialization"]

[docs]
readme = "README.md"

[[io.input]]
name = "items"
type = "array"
required = false
description = "Array of serialisable entries."

[[io.output]]
name = "text"
type = "string"
description = "JSON Lines string ending with a newline."

[deps]
requires = [
  "lcod://tooling/script@1"
]
