
schemaVersion = "1.0"
id = "lcod://tooling/value/is_string_nonempty@0.1.0"
name = "is_string_nonempty"
namespace = "tooling/value"
version = "0.1.0"
kind = "component"
summary = "Check whether a value is a non-empty string."

[deps]
requires = [
  "lcod://tooling/script@1"
]
