schemaVersion = "2.0"
id = "lcod://tooling/registry_sources/collect_queue@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Traverse the catalogue pointer queue breadth-first and emit inline contributions."

[deps]
requires = [
  "lcod://flow/if@1",
  "lcod://tooling/array/append@0.1.0",
  "lcod://tooling/array/length@0.1.0",
  "lcod://tooling/array/shift@0.1.0",
  "lcod://tooling/value/default_array@0.1.0",
  "lcod://tooling/registry_sources/normalize_pointer@0.1.0",
  "lcod://tooling/registry_sources/partition_normalized@0.1.0",
  "lcod://tooling/registry_sources/process_pointer@0.1.0",
  "lcod://tooling/registry_sources/build_inline_entry@0.1.0",
  "lcod://impl/set@1"
]

[inputs.queue]
summary = "Normalized pointers waiting to be processed."
required = false
schema = """
{
  "type": "array"
}"""

[inputs.downloadsRoot]
summary = "Directory used for downloaded catalogues."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.sourcesBaseDir]
summary = "Root directory for relative catalogue pointers."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.defaultEntrypoint]
summary = "Entrypoint defaults inherited by child pointers."
required = false
schema = """
{
  "type": "object"
}"""

[inputs.basePriority]
summary = "Base priority that should be forwarded to pointer helpers."
required = false
schema = "{}"

[outputs.contributions]
summary = "Inline contributions collected from processed catalogues."
schema = """
{
  "type": "array"
}"""

[outputs.warnings]
summary = "Warnings collected while processing the queue."
schema = """
{
  "type": "array"
}"""
