compose:
  - call: lcod://core/json/encode@0.1.0
    in:
      value: $.value
      space: $.indent
      sortKeys: $.sortKeys
      asciiOnly: $.asciiOnly
    out:
      encoded: $
  - call: lcod://flow/if@1
    in:
      cond: $.trailingNewline
    out:
      formatted: formatted
    slots:
      then:
        - call: lcod://core/string/format@0.1.0
          in:
            template: "{text}{newline}"
            values:
              text: $.encoded.text
              newline: "\n"
          out:
            formatted: $
      else:
        - call: lcod://impl/set@1
          in:
            formatted:
              value: $.encoded.text
          out:
            formatted: formatted
  - call: lcod://impl/set@1
    in:
      json: $.formatted.value
    out:
      json: json
