schemaVersion = "1.0"
id = "lcod://tooling/json/stringify@0.1.0"
name = "stringify"
namespace = "tooling/json"
version = "0.1.0"
kind = "component"

summary = "Serialize a value into JSON text using core/json/encode and append an optional newline."

[palette]
category = "JSON"
icon = "mdi:code-json"
tags = ["json", "serialization"]

[docs]
readme = "README.md"

[[io.input]]
name = "value"
type = "any"
required = true
description = "Value to serialize."

[[io.input]]
name = "indent"
type = "number"
required = false
description = "Number of spaces used for indentation (0-10)."

[[io.input]]
name = "sortKeys"
type = "boolean"
required = false
description = "Sort object keys alphabetically."

[[io.input]]
name = "asciiOnly"
type = "boolean"
required = false
description = "Escape non-ASCII characters."

[[io.input]]
name = "trailingNewline"
type = "boolean"
required = false
description = "Append a newline when true."

[[io.output]]
name = "json"
type = "string"
description = "Serialized JSON string (newline appended when requested)."

[deps]
requires = [
  "lcod://core/json/encode@0.1.0",
  "lcod://flow/if@1",
  "lcod://core/string/format@0.1.0",
  "lcod://impl/set@1"
]
