
schemaVersion = "1.0"
id = "lcod://tooling/json/stringify@0.1.0"
name = "stringify"
namespace = "tooling/json"
version = "0.1.0"
kind = "component"
summary = "Convert a JSON-compatible value into a string with optional indentation."

[deps]
requires = [
  "lcod://tooling/script@1"
]
