schemaVersion = "2.0"
id = "lcod://tooling/json/stringify@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Serialize a value into JSON text using core/json/encode and append an optional newline."

[palette]
category = "JSON"
icon = "mdi:code-json"
tags = [ "json", "serialization" ]

[deps]
requires = [
  "lcod://core/json/encode@0.1.0",
  "lcod://flow/if@1",
  "lcod://core/string/format@0.1.0",
  "lcod://impl/set@1"
]

[inputs.value]
summary = "Value to serialize."
required = true
schema = "{}"

[inputs.indent]
summary = "Number of spaces used for indentation (0-10)."
required = false
schema = """
{
  "type": "number"
}"""

[inputs.sortKeys]
summary = "Sort object keys alphabetically."
required = false
schema = """
{
  "type": "boolean"
}"""

[inputs.asciiOnly]
summary = "Escape non-ASCII characters."
required = false
schema = """
{
  "type": "boolean"
}"""

[inputs.trailingNewline]
summary = "Append a newline when true."
required = false
schema = """
{
  "type": "boolean"
}"""

[outputs.json]
summary = "Serialized JSON string (newline appended when requested)."
schema = """
{
  "type": "string"
}"""

[documentation]
body = "Serialize a value into JSON text using the standard JSON encode primitive."
