
schemaVersion = "1.0"
id = "lcod://tooling/array/append@0.1.0"
name = "append"
namespace = "tooling/array"
version = "0.1.0"
kind = "component"
summary = "Append a value to an array and return the new array."

[deps]
requires = [
  "lcod://tooling/script@1"
]
