schemaVersion = "2.0"
id = "lcod://tooling/array/append@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Append values to an array using the core/array/append primitive."

[palette]
category = "Array"
icon = "mdi:plus-box-outline"
tags = [ "array", "mutation" ]

[deps]
requires = [
  "lcod://tooling/value/is_array@0.1.0",
  "lcod://flow/if@1",
  "lcod://impl/set@1",
  "lcod://core/array/append@0.1.0"
]

[inputs.items]
summary = "Source array (defaults to an empty list)."
required = false
schema = """
{
  "type": "array"
}"""

[inputs.values]
summary = "Additional items appended before `value`."
required = false
schema = """
{
  "type": "array"
}"""

[inputs.value]
summary = "Single value appended when provided."
required = false
schema = "{}"

[outputs.items]
summary = "Updated array including the appended value."
schema = """
{
  "type": "array"
}"""

[outputs.length]
summary = "Length of the array after the append operation."
schema = """
{
  "type": "number"
}"""

[documentation]
body = """
Append values to an array without mutating the original list. Relies on the
standard `core/array/append@1` primitive."""
