schemaVersion = "1.0"
id = "lcod://tooling/array/append@0.1.0"
name = "append"
namespace = "tooling/array"
version = "0.1.0"
kind = "component"

summary = "Append values to an array using the core/array/append primitive."

[palette]
category = "Array"
icon = "mdi:plus-box-outline"
tags = ["array", "mutation"]

[docs]
readme = "README.md"

[[io.input]]
name = "items"
type = "array"
required = false
description = "Source array (defaults to an empty list)."

[[io.input]]
name = "values"
type = "array"
required = false
description = "Additional items appended before `value`."

[[io.input]]
name = "value"
type = "any"
required = false
description = "Single value appended when provided."

[[io.output]]
name = "items"
type = "array"
description = "Updated array including the appended value."

[[io.output]]
name = "length"
type = "number"
description = "Length of the array after the append operation."

[deps]
requires = [
  "lcod://tooling/value/is_array@0.1.0",
  "lcod://flow/if@1",
  "lcod://impl/set@1",
  "lcod://core/array/append@0.1.0"
]
