schemaVersion = "2.0"
id = "lcod://tooling/registry_catalog/normalize_package@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Validate and normalise a package entry."

[palette]
category = "Registry/Internal"
icon = "mdi:package-variant"
tags = [ "catalog", "normalize" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.entry]
summary = "Package entry from catalog.json."
required = true
schema = """
{
  "type": "object"
}"""

[outputs.ok]
summary = "True when the package entry is valid."
schema = """
{
  "type": "boolean"
}"""

[outputs.id]
summary = "Package identifier when valid."
schema = """
{
  "type": "string"
}"""

[outputs.registryId]
summary = "Associated registry identifier."
schema = """
{
  "type": "string"
}"""

[outputs.versionsPath]
summary = "Path to the versions document."
schema = """
{
  "type": "string"
}"""

[outputs.priority]
summary = "Package-level priority (nullable)."
schema = """
{
  "type": "number"
}"""

[outputs.warnings]
summary = "Issues detected while processing the package."
schema = """
{
  "type": "array"
}"""

[documentation]
body = "Validate and normalise a package entry."

[docs]
readme = "README.md"
