schemaVersion = "2.0"
id = "lcod://tooling/string/ensure_trailing_newline@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Ensure a string terminates with a newline."

[palette]
category = "Strings"
icon = "mdi:format-text"
tags = [ "string", "formatting" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.text]
summary = "Input string."
required = false
schema = """
{
  "type": "string"
}"""

[outputs.text]
summary = "String guaranteed to end with a newline."
schema = """
{
  "type": "string"
}"""

[documentation]
body = "Ensure a string terminates with a newline."
