
schemaVersion = "1.0"
id = "lcod://tooling/string/ensure_trailing_newline@0.1.0"
name = "ensure_trailing_newline"
namespace = "tooling/string"
version = "0.1.0"
kind = "component"
summary = "Ensure a string ends with a newline character."

[deps]
requires = [
  "lcod://tooling/script@1"
]
