schemaVersion = "1.0"
id = "lcod://tooling/array/compact@0.1.0"
name = "compact"
namespace = "tooling/array"
version = "0.1.0"
kind = "component"
summary = "Remove null and undefined entries from an array."

[deps]
requires = [
  "lcod://tooling/script@1"
]
