
schemaVersion = "1.0"
id = "lcod://tooling/registry_catalog/validate_package@0.1.0"
name = "validate_package"
namespace = "tooling/registry_catalog"
version = "0.1.0"
kind = "component"
summary = "Validate a single catalog package entry and produce error messages."

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://axiom/path/join@1",
  "lcod://axiom/fs/read-file@1"
]
