schemaVersion = "2.0"
id = "lcod://tooling/registry_catalog/validate_package@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Validate a single package entry and its manifests."

[palette]
category = "Registry/Internal"
icon = "mdi:package-search"
tags = [ "catalog", "validation" ]

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://axiom/path/join@1",
  "lcod://axiom/fs/read-file@1"
]

[inputs.rootPath]
summary = "Base directory used to resolve manifest and versions files."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.packageEntry]
summary = "Package definition extracted from catalog.json."
required = true
schema = """
{
  "type": "object"
}"""

[outputs.packageErrors]
summary = "Validation issues for the package."
schema = """
{
  "type": "array"
}"""

[outputs.packageId]
summary = "Canonical package identifier (when resolved)."
schema = """
{
  "type": "string"
}"""

[documentation]
body = "Validate a single package entry and its manifests."

[docs]
readme = "README.md"
