schemaVersion = "1.0"
id = "lcod://tooling/registry_catalog/validate_package@0.1.0"
name = "validate_package"
namespace = "tooling/registry_catalog"
version = "0.1.0"
kind = "component"

summary = "Validate a single package entry and its manifests."

[palette]
category = "Registry/Internal"
icon = "mdi:package-search"
tags = ["catalog", "validation"]

[docs]
readme = "README.md"

[[io.input]]
name = "rootPath"
type = "string"
required = false
description = "Base directory used to resolve manifest and versions files."

[[io.input]]
name = "packageEntry"
type = "object"
required = true
description = "Package definition extracted from catalog.json."

[[io.output]]
name = "packageErrors"
type = "array"
description = "Validation issues for the package."

[[io.output]]
name = "packageId"
type = "string"
description = "Canonical package identifier (when resolved)."

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://axiom/path/join@1",
  "lcod://axiom/fs/read-file@1"
]
