
schemaVersion = "1.0"
id = "lcod://tooling/value/is_object@0.1.0"
name = "is_object"
namespace = "tooling/value"
version = "0.1.0"
kind = "component"
summary = "Check whether a value is a non-null object (excluding arrays)."

[deps]
requires = [
  "lcod://tooling/script@1"
]
