schemaVersion = "1.0"
id = "lcod://tooling/registry_catalog/validate@0.1.0"
name = "validate"
namespace = "tooling/registry_catalog"
version = "0.1.0"
kind = "component"

summary = "Validate the registry catalog against structural and manifest rules."

[palette]
category = "Registry"
icon = "mdi:clipboard-check-outline"
tags = ["catalog", "validation"]

[docs]
readme = "README.md"

[[io.input]]
name = "rootPath"
type = "string"
required = false
description = "Base directory used to resolve catalog and package files."

[[io.input]]
name = "catalogPath"
type = "string"
required = false
description = "Path to catalog.json relative to rootPath."

[[io.output]]
name = "errors"
type = "array"
description = "Validation errors (empty array means the catalogue is valid)."

[[io.output]]
name = "packages"
type = "array"
description = "Per-package diagnostics produced during validation."

[deps]
requires = [
  "lcod://impl/set@1",
  "lcod://flow/if@1",
  "lcod://flow/foreach@1",
  "lcod://tooling/json/read_file@0.1.0",
  "lcod://tooling/value/is_array@0.1.0",
  "lcod://tooling/value/is_string_nonempty@0.1.0",
  "lcod://tooling/array/append@0.1.0",
  "lcod://tooling/array/flatten@0.1.0",
  "lcod://tooling/array/pluck@0.1.0",
  "lcod://tooling/array/find_duplicates@0.1.0",
  "lcod://tooling/registry_catalog/validate_package@0.1.0"
]
