schemaVersion = "1.0"
id = "lcod://tooling/registry_catalog/normalize_versions_doc@0.1.0"
name = "normalize_versions_doc"
namespace = "tooling/registry_catalog"
version = "0.1.0"
kind = "component"
summary = "Normalize the versions document referenced by a catalog package."

[deps]
requires = [
  "lcod://tooling/script@1"
]
