schemaVersion = "2.0"
id = "lcod://tooling/registry_catalog/normalize_versions_doc@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Normalise a versions document."

[palette]
category = "Registry/Internal"
icon = "mdi:file-document-outline"
tags = [ "catalog", "normalize" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.doc]
summary = "Parsed versions document."
required = false
schema = """
{
  "type": "object"
}"""

[outputs.versions]
summary = "Filtered list of version entries."
schema = """
{
  "type": "array"
}"""

[outputs.warnings]
summary = "Issues detected while parsing the document."
schema = """
{
  "type": "array"
}"""

[documentation]
body = "Normalise a versions document."
