name: Verify Components

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      LCOD_RESOLVER_PATH: ${{ github.workspace }}
      LCOD_RUN_VERSION: "0.1.12"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install repo dependencies
        run: npm install --no-fund --no-audit

      - name: Download lcod-run
        run: |
          set -euo pipefail
          curl -sSL -o lcod-run.tar.gz https://github.com/lcod-team/lcod-kernel-rs/releases/download/lcod-run-v${LCOD_RUN_VERSION}/lcod-run-linux-x86_64.tar.gz
          tar -xzf lcod-run.tar.gz
          chmod +x lcod-run

      - name: Prepare state
        run: echo '{"projectPath":"'"${{ github.workspace }}/packages/std"'"}' > state.json

      - name: Run metadata verification
        run: ./lcod-run --compose tests/components.verify.metadata.yaml

      - name: Run registry component tests
        run: ./lcod-run --compose tests/components.registry.yaml --input state.json

      - name: Run component unit tests
        run: ./lcod-run --compose tests/components.registry.tests.yaml --input state.json

      - name: Export components manifest
        run: npm run export:components

      - name: Ensure manifest is up to date
        run: |
          if git diff --quiet registry/components.std.json; then
            echo "components.std.json is up to date"
          else
            echo "::error::registry/components.std.json is out of date. Run 'npm run export:components' locally and commit the changes." >&2
            git diff registry/components.std.json
            exit 1
          fi
